include:
  remote: 'https://gitlab.inria.fr/compose/include/compose-publish/-/raw/master/.compose-gitlab-ci.yml'

buildrawlatex:
  script:
    - echo $CI_PROJECT_NAME
  rules:
  - if: $CI_COMMIT_BRANCH == "master" && $CI_PROJECT_NAME =~ /mini-chameleon/

pages:
  rules:
  - if: $CI_COMMIT_BRANCH == "master" && $CI_PROJECT_NAME =~ /mini-chameleon/

# before_script:
#   # Use a fixed GUIX profile for maximum reproducibility:
#   - mkdir -p $HOME/.guix-extra/compose/
#   - >
#        guix pull --channels=.guix-extra/channels-compose-fixed.scm
#        --profile=$HOME/.guix-extra/compose/guix --allow-downgrades
#   - export GUIX_PROFILE="$HOME/.guix-extra/compose/guix"
#   - . "$GUIX_PROFILE/etc/profile"
#   - mkdir -p public/
#   - guix describe --format=channels | tee public/channels.scm
